### ISSUE TITLE
UX improvment (opinion)

### ISSUE THREAD

**Issue by metju90** [morloy/ledgy.com#102]
This is not an issue per se. it is a recommendation.

When users lands on any page, the initial HTML response from the server contains all the assets and two particular sections, the "try" and the footer. While the main JS bundle is being parsed, the HTML provided by the server ("try" and the footer") is painted in the browser.

As soon as the JS bundle is ready and  React renders the application, the transition is not smooth and it is causing a flicker. The "issue" can be seen here https://app.hyfy.io/share/abcHTsYvgmn/

If this is an issue for you, i'd recommend to use a loading page. An example can be seen here: https://igame.com

**Comment by morloy** [comment]
True. The content should be in the initial HTML, but I think this got lost during the upgrade from Gatsby v1 to v2.

**Comment by morloy** [comment]
Just checked, and the initial HTML includes all the content. But once you visit the site for the first time, the service worker chaches the skeleton and the content. Thus, when you load a second time, the browser first shows the skeleton from the SW and then renders the content. (When you click ‘Show Source’ in Chrome it shows the cached HTML.)
